version: '3'

services: 
  client_and_api:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    ports:
      - 3000:8080
    volumes: 
      - ./public:/var/www/html
      - ./src/server:/var/www/src/server
      - ./vendor:/var/www/vendor