version: '3'

networks:
  default:
    external:
      name: dnaiq-net

services: 
  dnaiq-api:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    ports:
      - 3000:8080
    volumes: 
      - ./public:/var/www/html
      - ./src/server:/var/www/src/server
      - ./vendor:/var/www/vendor